iPad (Mac Catalyst) Interaction Support
LiulietLee/BilibiliCD pull request #28
Opened 2020-03-27 11:15 UTC by ApolloZhu

- Add UIPointerInteraction for iOS 13.4
- Toggle show hidden history with Cmd + Shift + A
- Import LLDialog through Swift Package Manager

2020-03-29 08:25 UTC, LiulietLee requested changes
在 Mac 上打开 App 然后去复制一个链接，回来之后通过菜单再进一次搜索页，这时 navigation bar 会消失掉。

另外 Tutorial 可能也需要重新摆一下图的位置。

2020-03-29 08:29 UTC, ApolloZhu commented
nav bar 消失我之后看一看

虽然 Mac 引导图显示不全但我看重点都还在，但最主要的问题是...理论上 Mac 引导图是需要完全换成 Mac 上的操作方法？

2020-03-29 09:03 UTC, LiulietLee commented
确实，所以需要重新截图（App 大小++

Liuliet.Lee

在 2020年3月29日，16:29，ApolloZhu <notifications@github.com> 写道：

﻿

nav bar 消失我之后看一看

虽然 Mac 引导图显示不全但我看重点都还在，但最主要的问题是...理论上 Mac 引导图是需要完全换成 Mac 上的操作方法？

—
You are receiving this because your review was requested.
Reply to this email directly, view it on GitHub<https://github.com/LiulietLee/BilibiliCD/pull/28#issuecomment-605603163>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ACKPSWRFSG5JFSYZOPK7DY3RJ4BHJANCNFSM4LU5V3YA>.

2020-03-31 16:18 UTC, LiulietLee approved these changes

2020-03-31 16:19 UTC, merged

2020-03-31 23:27 UTC, ApolloZhu commented
建议少用  squash merge，理论上单个 commit 太大不是好习惯。